import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ProductCarousel from "@/components/home/ourProduct/ProductCarousel";
import Hero from "@/components/home/hero/Hero";
import Outlet from "@/components/home/our-outlet/Outlet";
import Banner from "@/components/home/banner/Banner";
import CardGallery from "@/components/home/CardGallery/CardGallery";
import HeaderHero from "@/components/home/HeaderHero";

const inter = Inter({ subsets: ["latin"] });
export const getStaticProps = async () => {
  const res = await fetch(
    // "https://jsonplaceholder.typicode.com/posts"
    "https://crabby-pocketbook-eel.cyclic.app/api/v1/product"
  );
  const data = await res.json();
  return {
    props: { data },
    revalidate: 3,
  };
};
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Sultan Tea</title>
        <meta name="description" content="Generated by Zoomit app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* follow this for folder structure */}
        {/* https://github.com/leerob/leerob.io */}
        <HeaderHero />
        <Hero className="heroPosition" />
        <ProductCarousel data={data} />

        <Banner />
        <CardGallery />
        <Outlet />
      </main>
    </>
  );
}
