import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/home/hero/Hero'
import Product from '@/components/home/ourProduct/Product'
import Banner from '@/components/home/banner/Banner'
import CardGallery from '@/components/home/CardGallery/CardGallery'
import Outlet from '@/components/home/our-outlet/Outlet'
import OurOffices from '@/components/home/our-offices/OurOffices'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>         
                {/* follow this for folder structure */}
                {/* https://github.com/leerob/leerob.io */}
                <Hero />
                <Product />
                <Banner />
                <CardGallery/>
                <Outlet />
                <OurOffices />         
 
      </main>
    </>
  )
}
